// <auto-generated />
using System;
using Class_Library.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Class_Library.Migrations
{
    [DbContext(typeof(InventoryManagementContext))]
    partial class InventoryManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Class_Library.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("username");

                    b.ToTable("tbUser");

                    b.HasData(
                        new
                        {
                            username = "admin",
                            fullname = "Administrator",
                            password = "admin123",
                            phone = "01000000000",
                            role = 1
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Category", b =>
                {
                    b.Property<int>("catid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("catid"));

                    b.Property<string>("catname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("catid");

                    b.ToTable("tbCategory");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Customer", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cid"));

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cphone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("cid");

                    b.ToTable("tbCustomer");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Order", b =>
                {
                    b.Property<int>("oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("oid"));

                    b.Property<int>("cid")
                        .HasColumnType("int");

                    b.Property<DateTime>("odate")
                        .HasColumnType("datetime2");

                    b.Property<int>("pid")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.HasKey("oid");

                    b.HasIndex("cid");

                    b.HasIndex("pid");

                    b.ToTable("tbOrder");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Product", b =>
                {
                    b.Property<int>("pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pid"));

                    b.Property<int?>("catid")
                        .HasColumnType("int");

                    b.Property<string>("pdescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("pname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("pprice")
                        .HasColumnType("int");

                    b.Property<int>("pqty")
                        .HasColumnType("int");

                    b.HasKey("pid");

                    b.HasIndex("catid");

                    b.ToTable("tbProduct");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Order", b =>
                {
                    b.HasOne("InventoryManagementSystem.ClassLibrary.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.ClassLibrary.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Product", b =>
                {
                    b.HasOne("InventoryManagementSystem.ClassLibrary.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("catid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("InventoryManagementSystem.ClassLibrary.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
